---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: test-node
  name: test-node
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-node
  template:
    metadata:
      labels:
        app: test-node
    spec:
      containers:
        - name: test-node
          image: nginx
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            requests:
              memory: "256M"
              cpu: "256m"
            limits:
              memory: "512M"
              cpu: "512m"


---
apiVersion: v1
kind: Service
metadata:
  name: test-node-service
  namespace: default
  labels:
    app: test-node-service
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: test-node
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
  name: test-node-ingress
  namespace: default
spec:
  rules:
    - host: site.diegoteste.tk
      http:
        paths:
          - path: /
            backend:
              serviceName:  test-node-service
              servicePort: 80

